### ISSUE TITLE
For 1bit mode rest pins:DATA1-DATA3 are set and it causes pin re-use error.

### ISSUE THREAD

**Issue by elproko** [n-serrette/esphome_sd_card#3]
Error below:
```
Failed config

sd_mmc_card: [source /config/esphome/ip86_lvgl1.yaml:146]
  
  Pin XX is used in multiple places.
  id: sd_card
  mode_1bit: True
  clk_pin: 
    number: 18
    mode: 
      output: True
      input: False
      open_drain: False
      pullup: False
      pulldown: False
    inverted: False
    ignore_pin_validation_error: False
```

**Comment by n-serrette** [comment]
Hi,
thanks for your interest in this project.
I have done a quick fix on the branch ```fix_3_pin_default```, I have remove the default value in the component schema for ```data1_pin``` to ```data3_pin```.
Could you confirm it work properly ?

**Comment by elproko** [comment]
First of all - I really appreciate your work. I do not know why there is no native support for SD card under ESPHome.
I tried my own approach [(esp-cam-logger writing on SD card)](https://github.com/elproko/esphome_related/tree/main/esp-cam-logger) but I like yours much more.

Thanks for fast response. Unfortunately I didn't notice it fast enough.

I have 2 answers for you :)

1. - good - it works on ESP-CAM module where I do not use GPIOs 12 & 13.
2. - not good - on other board where there are other things.

Details:

yaml config:

```
sd_mmc_card:
  id: my_sd_card
  mode_1bit: true
  clk_pin: GPIO18
  cmd_pin: GPIO23
  data0_pin: GPIO19
```

Error during compilation phase:
```
Failed config

spi: [source /config/esphome/ip86_lvgl1.yaml:137]
  
  Pin 13 is used in multiple places.
  - id: spi_lcd
    clk_pin: 
      number: 14
      mode: 
        output: True
        input: False
        open_drain: False
        pullup: False
        pulldown: False
      inverted: False
      ignore_pin_validation_error: False
      ignore_strapping_warning: False
sd_mmc_card: [source /config/esphome/ip86_lvgl1.yaml:154]
  
  Pin 13 is used in multiple places.
  id: my_sd_card
  mode_1bit: True
  clk_pin: 
    number: 18
    mode: 
      output: True
      input: False
      open_drain: False
      pullup: False
      pulldown: False
    inverted: False
    ignore_pin_validation_error: False
Pin 12 is used in multiple places

Pin 12 is used in multiple places
```

**Comment by elproko** [comment]
Created PR for this. Please look: [PR:4](https://github.com/n-serrette/esphome_sd_card/pull/4)

**Comment by n-serrette** [comment]
thanks for your feedback, I will take a look at your PR
